name: CraftplayShop
version: 0.1.0
main: de.craftplay.shop.CraftplayShopPlugin
api-version: '1.21'
author: Wullverin
website: https://Craftplay.de
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - WorldGuard
  - PlotSquared
  - Lands
  - BentoBox
  - floodgate
  - Citizens
commands:
  shop:
    description: Öffnet CraftplayShop.
    aliases: [craftplayshop]
  cshop:
    description: Admin-Befehl für CraftplayShop.
  servershop:
    description: Öffnet den ServerShop.
  sellhand:
    description: Verkauft das Item in deiner Hand.
  sellall:
    description: Verkauft alle ankaufbaren Items aus deinem Inventar.
  sellgui:
    description: Öffnet das Verkauf-GUI.
    aliases: [sellinventory, sellinv]
  trade:
    description: DirectTrade Einstellungen und später Handel.
  asc:
    description: AutoSellChest.
    aliases: [autosellchest, sellchest, verkaufskiste]
permissions:
  craftplayshop.use:
    default: true
  craftplayshop.admin:
    default: op
  craftplayshop.reload:
    default: op
  craftplayshop.servershop.use:
    default: true
  craftplayshop.servershop.buy:
    default: true
  craftplayshop.servershop.sell:
    default: true
  craftplayshop.servershop.sellhand:
    default: true
  craftplayshop.servershop.sellall:
    default: true
  craftplayshop.servershop.sellgui:
    default: true
  craftplayshop.playershop.use:
    default: true
  craftplayshop.playershop.create:
    default: true
  craftplayshop.playershop.buy:
    default: true
  craftplayshop.playershop.admin:
    default: op
  craftplayshop.language:
    default: true
  craftplayshop.trade.use:
    default: true
  craftplayshop.trade.toggle:
    default: true
  craftplayshop.trade.request:
    default: true
  craftplayshop.trade.accept:
    default: true
  craftplayshop.autosellchest.use:
    default: true
  craftplayshop.autosellchest.create:
    default: true
  craftplayshop.autosellchest.admin:
    default: op
