name: CraftplayShop
version: 1.0.0
main: de.craftplay.shop.CraftplayShopPlugin
api-version: '1.21'
author: Wullverin
website: https://Craftplay.de
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - HeadDatabase
  - WorldGuard
  - PlotSquared
  - Lands
  - BentoBox
  - floodgate
  - Citizens
commands:
  shop:
    description: Opens CraftplayShop.
    aliases: [craftplayshop]
  cshop:
    description: Admin command for CraftplayShop.
  servershop:
    description: Opens the ServerShop.
  sellhand:
    description: Sells the item in your hand.
  sellall:
    description: Sells all sellable items from your inventory.
  sellgui:
    description: Opens the sell GUI.
    aliases: [sellinventory, sellinv]
  trade:
    description: DirectTrade settings and trading.
  ah:
    description: Opens the AuctionHouse.
    aliases: [auctionhouse]
  asc:
    description: AutoSellChest.
    aliases: [autosellchest, sellchest, verkaufskiste]
permissions:
  craftplayshop.use:
    default: true
  craftplayshop.admin:
    default: op
  craftplayshop.reload:
    default: op
  craftplayshop.servershop.use:
    default: true
  craftplayshop.servershop.buy:
    default: true
  craftplayshop.servershop.sell:
    default: true
  craftplayshop.servershop.sellhand:
    default: true
  craftplayshop.servershop.sellall:
    default: true
  craftplayshop.servershop.sellgui:
    default: true
  craftplayshop.playershop.use:
    default: true
  craftplayshop.playershop.create:
    default: true
  craftplayshop.playershop.buy:
    default: true
  craftplayshop.playershop.sell:
    default: true
  craftplayshop.playershop.edit:
    default: true
  craftplayshop.playershop.admin:
    default: op
  craftplayshop.language:
    default: true
  craftplayshop.trade.use:
    default: true
  craftplayshop.trade.toggle:
    default: true
  craftplayshop.trade.request:
    default: true
  craftplayshop.trade.accept:
    default: true
  craftplayshop.auctionhouse.use:
    default: true
  craftplayshop.auctionhouse.sell:
    default: true
  craftplayshop.auctionhouse.buy:
    default: true
  craftplayshop.auctionhouse.admin:
    default: op
  craftplayshop.rankshop.use:
    default: true
  craftplayshop.permissionshop.use:
    default: true
  craftplayshop.referral.use:
    default: true
  craftplayshop.autosellchest.use:
    default: true
  craftplayshop.autosellchest.create:
    default: true
  craftplayshop.autosellchest.trust:
    default: true
  craftplayshop.autosellchest.admin:
    default: op
  craftplayshop.autosellchest.upgrade.interval.2:
    default: true
  craftplayshop.autosellchest.upgrade.interval.3:
    default: op
  craftplayshop.autosellchest.upgrade.multiplier.2:
    default: true
  craftplayshop.autosellchest.upgrade.multiplier.3:
    default: op
